# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-05-10 01:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_reader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date1', models.DateField()),
                ('date2', models.DateField(null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Book')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Reader')),
            ],
        ),
    ]
