# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-05-10 01:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_circulation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circulation',
            old_name='date1',
            new_name='date_checkout',
        ),
        migrations.RenameField(
            model_name='circulation',
            old_name='date2',
            new_name='date_return',
        ),
    ]
